// Auto-generated by LibreLane
module CPU_TOP(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  output[31:0] imem_addr,
  input[31:0] imem_data,
  output[31:0] dmem_addr,
  output[31:0] dmem_wdata,
  input[31:0] dmem_rdata,
  output dmem_rd,
  output dmem_wr,
  input[7:0] io_addr,
  output[31:0] io_wdata,
  input[31:0] io_rdata,
  output io_rd,
  output io_wr
);
endmodule
